// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh4ltJ1s9Ca_siAwoIxhObW38sv4XXx0Q',
    appId: '1:457482752709:web:1cc368cfdefceffa8c16ac',
    messagingSenderId: '457482752709',
    projectId: 'agrimoe-7b917',
    authDomain: 'agrimoe-7b917.firebaseapp.com',
    storageBucket: 'agrimoe-7b917.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATD4dNmRDvnxb4FT0FzNktjuHwvXcLB7g',
    appId: '1:457482752709:android:616b98a914bb7b4a8c16ac',
    messagingSenderId: '457482752709',
    projectId: 'agrimoe-7b917',
    storageBucket: 'agrimoe-7b917.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcLV0LzoQ_E5XrnBeG-gXjCquFnLqcPVI',
    appId: '1:457482752709:ios:f92301d4122836478c16ac',
    messagingSenderId: '457482752709',
    projectId: 'agrimoe-7b917',
    storageBucket: 'agrimoe-7b917.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcLV0LzoQ_E5XrnBeG-gXjCquFnLqcPVI',
    appId: '1:457482752709:ios:f92301d4122836478c16ac',
    messagingSenderId: '457482752709',
    projectId: 'agrimoe-7b917',
    storageBucket: 'agrimoe-7b917.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6KHPlsgWejaB-Q1XSBg9Jv6dnYp0dyT0',
    appId: '1:457482752709:web:c504e51367d2bda98c16ac',
    messagingSenderId: '457482752709',
    projectId: 'agrimoe-7b917',
    authDomain: 'agrimoe-7b917.firebaseapp.com',
    storageBucket: 'agrimoe-7b917.appspot.com',
  );
}
